/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef KeyValueStore_H
#define KeyValueStore_H

#include <thrift/TDispatchProcessor.h>
#include "KeyValueStore_types.h"

namespace KeyValueStore {

class KeyValueStoreIf {
 public:
  virtual ~KeyValueStoreIf() {}
  virtual void Get(GetResponse& _return, const std::string& key) = 0;
  virtual void GetList(GetListResponse& _return, const std::string& key) = 0;
  virtual KVStoreStatus::type Put(const std::string& key, const std::string& value, const std::string& clientid) = 0;
  virtual KVStoreStatus::type AddToList(const std::string& key, const std::string& value, const std::string& clientid) = 0;
  virtual KVStoreStatus::type RemoveFromList(const std::string& key, const std::string& value, const std::string& clientid) = 0;
};

class KeyValueStoreIfFactory {
 public:
  typedef KeyValueStoreIf Handler;

  virtual ~KeyValueStoreIfFactory() {}

  virtual KeyValueStoreIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(KeyValueStoreIf* /* handler */) = 0;
};

class KeyValueStoreIfSingletonFactory : virtual public KeyValueStoreIfFactory {
 public:
  KeyValueStoreIfSingletonFactory(const boost::shared_ptr<KeyValueStoreIf>& iface) : iface_(iface) {}
  virtual ~KeyValueStoreIfSingletonFactory() {}

  virtual KeyValueStoreIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(KeyValueStoreIf* /* handler */) {}

 protected:
  boost::shared_ptr<KeyValueStoreIf> iface_;
};

class KeyValueStoreNull : virtual public KeyValueStoreIf {
 public:
  virtual ~KeyValueStoreNull() {}
  void Get(GetResponse& /* _return */, const std::string& /* key */) {
    return;
  }
  void GetList(GetListResponse& /* _return */, const std::string& /* key */) {
    return;
  }
  KVStoreStatus::type Put(const std::string& /* key */, const std::string& /* value */, const std::string& /* clientid */) {
    KVStoreStatus::type _return = (KVStoreStatus::type)0;
    return _return;
  }
  KVStoreStatus::type AddToList(const std::string& /* key */, const std::string& /* value */, const std::string& /* clientid */) {
    KVStoreStatus::type _return = (KVStoreStatus::type)0;
    return _return;
  }
  KVStoreStatus::type RemoveFromList(const std::string& /* key */, const std::string& /* value */, const std::string& /* clientid */) {
    KVStoreStatus::type _return = (KVStoreStatus::type)0;
    return _return;
  }
};

typedef struct _KeyValueStore_Get_args__isset {
  _KeyValueStore_Get_args__isset() : key(false) {}
  bool key;
} _KeyValueStore_Get_args__isset;

class KeyValueStore_Get_args {
 public:

  KeyValueStore_Get_args() : key() {
  }

  virtual ~KeyValueStore_Get_args() throw() {}

  std::string key;

  _KeyValueStore_Get_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  bool operator == (const KeyValueStore_Get_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const KeyValueStore_Get_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KeyValueStore_Get_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class KeyValueStore_Get_pargs {
 public:


  virtual ~KeyValueStore_Get_pargs() throw() {}

  const std::string* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KeyValueStore_Get_result__isset {
  _KeyValueStore_Get_result__isset() : success(false) {}
  bool success;
} _KeyValueStore_Get_result__isset;

class KeyValueStore_Get_result {
 public:

  KeyValueStore_Get_result() {
  }

  virtual ~KeyValueStore_Get_result() throw() {}

  GetResponse success;

  _KeyValueStore_Get_result__isset __isset;

  void __set_success(const GetResponse& val) {
    success = val;
  }

  bool operator == (const KeyValueStore_Get_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const KeyValueStore_Get_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KeyValueStore_Get_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KeyValueStore_Get_presult__isset {
  _KeyValueStore_Get_presult__isset() : success(false) {}
  bool success;
} _KeyValueStore_Get_presult__isset;

class KeyValueStore_Get_presult {
 public:


  virtual ~KeyValueStore_Get_presult() throw() {}

  GetResponse* success;

  _KeyValueStore_Get_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _KeyValueStore_GetList_args__isset {
  _KeyValueStore_GetList_args__isset() : key(false) {}
  bool key;
} _KeyValueStore_GetList_args__isset;

class KeyValueStore_GetList_args {
 public:

  KeyValueStore_GetList_args() : key() {
  }

  virtual ~KeyValueStore_GetList_args() throw() {}

  std::string key;

  _KeyValueStore_GetList_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  bool operator == (const KeyValueStore_GetList_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const KeyValueStore_GetList_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KeyValueStore_GetList_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class KeyValueStore_GetList_pargs {
 public:


  virtual ~KeyValueStore_GetList_pargs() throw() {}

  const std::string* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KeyValueStore_GetList_result__isset {
  _KeyValueStore_GetList_result__isset() : success(false) {}
  bool success;
} _KeyValueStore_GetList_result__isset;

class KeyValueStore_GetList_result {
 public:

  KeyValueStore_GetList_result() {
  }

  virtual ~KeyValueStore_GetList_result() throw() {}

  GetListResponse success;

  _KeyValueStore_GetList_result__isset __isset;

  void __set_success(const GetListResponse& val) {
    success = val;
  }

  bool operator == (const KeyValueStore_GetList_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const KeyValueStore_GetList_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KeyValueStore_GetList_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KeyValueStore_GetList_presult__isset {
  _KeyValueStore_GetList_presult__isset() : success(false) {}
  bool success;
} _KeyValueStore_GetList_presult__isset;

class KeyValueStore_GetList_presult {
 public:


  virtual ~KeyValueStore_GetList_presult() throw() {}

  GetListResponse* success;

  _KeyValueStore_GetList_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _KeyValueStore_Put_args__isset {
  _KeyValueStore_Put_args__isset() : key(false), value(false), clientid(false) {}
  bool key;
  bool value;
  bool clientid;
} _KeyValueStore_Put_args__isset;

class KeyValueStore_Put_args {
 public:

  KeyValueStore_Put_args() : key(), value(), clientid() {
  }

  virtual ~KeyValueStore_Put_args() throw() {}

  std::string key;
  std::string value;
  std::string clientid;

  _KeyValueStore_Put_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  void __set_value(const std::string& val) {
    value = val;
  }

  void __set_clientid(const std::string& val) {
    clientid = val;
  }

  bool operator == (const KeyValueStore_Put_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    if (!(clientid == rhs.clientid))
      return false;
    return true;
  }
  bool operator != (const KeyValueStore_Put_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KeyValueStore_Put_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class KeyValueStore_Put_pargs {
 public:


  virtual ~KeyValueStore_Put_pargs() throw() {}

  const std::string* key;
  const std::string* value;
  const std::string* clientid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KeyValueStore_Put_result__isset {
  _KeyValueStore_Put_result__isset() : success(false) {}
  bool success;
} _KeyValueStore_Put_result__isset;

class KeyValueStore_Put_result {
 public:

  KeyValueStore_Put_result() : success((KVStoreStatus::type)0) {
  }

  virtual ~KeyValueStore_Put_result() throw() {}

  KVStoreStatus::type success;

  _KeyValueStore_Put_result__isset __isset;

  void __set_success(const KVStoreStatus::type val) {
    success = val;
  }

  bool operator == (const KeyValueStore_Put_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const KeyValueStore_Put_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KeyValueStore_Put_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KeyValueStore_Put_presult__isset {
  _KeyValueStore_Put_presult__isset() : success(false) {}
  bool success;
} _KeyValueStore_Put_presult__isset;

class KeyValueStore_Put_presult {
 public:


  virtual ~KeyValueStore_Put_presult() throw() {}

  KVStoreStatus::type* success;

  _KeyValueStore_Put_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _KeyValueStore_AddToList_args__isset {
  _KeyValueStore_AddToList_args__isset() : key(false), value(false), clientid(false) {}
  bool key;
  bool value;
  bool clientid;
} _KeyValueStore_AddToList_args__isset;

class KeyValueStore_AddToList_args {
 public:

  KeyValueStore_AddToList_args() : key(), value(), clientid() {
  }

  virtual ~KeyValueStore_AddToList_args() throw() {}

  std::string key;
  std::string value;
  std::string clientid;

  _KeyValueStore_AddToList_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  void __set_value(const std::string& val) {
    value = val;
  }

  void __set_clientid(const std::string& val) {
    clientid = val;
  }

  bool operator == (const KeyValueStore_AddToList_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    if (!(clientid == rhs.clientid))
      return false;
    return true;
  }
  bool operator != (const KeyValueStore_AddToList_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KeyValueStore_AddToList_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class KeyValueStore_AddToList_pargs {
 public:


  virtual ~KeyValueStore_AddToList_pargs() throw() {}

  const std::string* key;
  const std::string* value;
  const std::string* clientid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KeyValueStore_AddToList_result__isset {
  _KeyValueStore_AddToList_result__isset() : success(false) {}
  bool success;
} _KeyValueStore_AddToList_result__isset;

class KeyValueStore_AddToList_result {
 public:

  KeyValueStore_AddToList_result() : success((KVStoreStatus::type)0) {
  }

  virtual ~KeyValueStore_AddToList_result() throw() {}

  KVStoreStatus::type success;

  _KeyValueStore_AddToList_result__isset __isset;

  void __set_success(const KVStoreStatus::type val) {
    success = val;
  }

  bool operator == (const KeyValueStore_AddToList_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const KeyValueStore_AddToList_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KeyValueStore_AddToList_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KeyValueStore_AddToList_presult__isset {
  _KeyValueStore_AddToList_presult__isset() : success(false) {}
  bool success;
} _KeyValueStore_AddToList_presult__isset;

class KeyValueStore_AddToList_presult {
 public:


  virtual ~KeyValueStore_AddToList_presult() throw() {}

  KVStoreStatus::type* success;

  _KeyValueStore_AddToList_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _KeyValueStore_RemoveFromList_args__isset {
  _KeyValueStore_RemoveFromList_args__isset() : key(false), value(false), clientid(false) {}
  bool key;
  bool value;
  bool clientid;
} _KeyValueStore_RemoveFromList_args__isset;

class KeyValueStore_RemoveFromList_args {
 public:

  KeyValueStore_RemoveFromList_args() : key(), value(), clientid() {
  }

  virtual ~KeyValueStore_RemoveFromList_args() throw() {}

  std::string key;
  std::string value;
  std::string clientid;

  _KeyValueStore_RemoveFromList_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  void __set_value(const std::string& val) {
    value = val;
  }

  void __set_clientid(const std::string& val) {
    clientid = val;
  }

  bool operator == (const KeyValueStore_RemoveFromList_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    if (!(clientid == rhs.clientid))
      return false;
    return true;
  }
  bool operator != (const KeyValueStore_RemoveFromList_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KeyValueStore_RemoveFromList_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class KeyValueStore_RemoveFromList_pargs {
 public:


  virtual ~KeyValueStore_RemoveFromList_pargs() throw() {}

  const std::string* key;
  const std::string* value;
  const std::string* clientid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KeyValueStore_RemoveFromList_result__isset {
  _KeyValueStore_RemoveFromList_result__isset() : success(false) {}
  bool success;
} _KeyValueStore_RemoveFromList_result__isset;

class KeyValueStore_RemoveFromList_result {
 public:

  KeyValueStore_RemoveFromList_result() : success((KVStoreStatus::type)0) {
  }

  virtual ~KeyValueStore_RemoveFromList_result() throw() {}

  KVStoreStatus::type success;

  _KeyValueStore_RemoveFromList_result__isset __isset;

  void __set_success(const KVStoreStatus::type val) {
    success = val;
  }

  bool operator == (const KeyValueStore_RemoveFromList_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const KeyValueStore_RemoveFromList_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KeyValueStore_RemoveFromList_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KeyValueStore_RemoveFromList_presult__isset {
  _KeyValueStore_RemoveFromList_presult__isset() : success(false) {}
  bool success;
} _KeyValueStore_RemoveFromList_presult__isset;

class KeyValueStore_RemoveFromList_presult {
 public:


  virtual ~KeyValueStore_RemoveFromList_presult() throw() {}

  KVStoreStatus::type* success;

  _KeyValueStore_RemoveFromList_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class KeyValueStoreClient : virtual public KeyValueStoreIf {
 public:
  KeyValueStoreClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  KeyValueStoreClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void Get(GetResponse& _return, const std::string& key);
  void send_Get(const std::string& key);
  void recv_Get(GetResponse& _return);
  void GetList(GetListResponse& _return, const std::string& key);
  void send_GetList(const std::string& key);
  void recv_GetList(GetListResponse& _return);
  KVStoreStatus::type Put(const std::string& key, const std::string& value, const std::string& clientid);
  void send_Put(const std::string& key, const std::string& value, const std::string& clientid);
  KVStoreStatus::type recv_Put();
  KVStoreStatus::type AddToList(const std::string& key, const std::string& value, const std::string& clientid);
  void send_AddToList(const std::string& key, const std::string& value, const std::string& clientid);
  KVStoreStatus::type recv_AddToList();
  KVStoreStatus::type RemoveFromList(const std::string& key, const std::string& value, const std::string& clientid);
  void send_RemoveFromList(const std::string& key, const std::string& value, const std::string& clientid);
  KVStoreStatus::type recv_RemoveFromList();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class KeyValueStoreProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<KeyValueStoreIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (KeyValueStoreProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_Get(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_GetList(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_Put(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_AddToList(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_RemoveFromList(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  KeyValueStoreProcessor(boost::shared_ptr<KeyValueStoreIf> iface) :
    iface_(iface) {
    processMap_["Get"] = &KeyValueStoreProcessor::process_Get;
    processMap_["GetList"] = &KeyValueStoreProcessor::process_GetList;
    processMap_["Put"] = &KeyValueStoreProcessor::process_Put;
    processMap_["AddToList"] = &KeyValueStoreProcessor::process_AddToList;
    processMap_["RemoveFromList"] = &KeyValueStoreProcessor::process_RemoveFromList;
  }

  virtual ~KeyValueStoreProcessor() {}
};

class KeyValueStoreProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  KeyValueStoreProcessorFactory(const ::boost::shared_ptr< KeyValueStoreIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< KeyValueStoreIfFactory > handlerFactory_;
};

class KeyValueStoreMultiface : virtual public KeyValueStoreIf {
 public:
  KeyValueStoreMultiface(std::vector<boost::shared_ptr<KeyValueStoreIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~KeyValueStoreMultiface() {}
 protected:
  std::vector<boost::shared_ptr<KeyValueStoreIf> > ifaces_;
  KeyValueStoreMultiface() {}
  void add(boost::shared_ptr<KeyValueStoreIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void Get(GetResponse& _return, const std::string& key) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Get(_return, key);
    }
    ifaces_[i]->Get(_return, key);
    return;
  }

  void GetList(GetListResponse& _return, const std::string& key) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetList(_return, key);
    }
    ifaces_[i]->GetList(_return, key);
    return;
  }

  KVStoreStatus::type Put(const std::string& key, const std::string& value, const std::string& clientid) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Put(key, value, clientid);
    }
    return ifaces_[i]->Put(key, value, clientid);
  }

  KVStoreStatus::type AddToList(const std::string& key, const std::string& value, const std::string& clientid) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->AddToList(key, value, clientid);
    }
    return ifaces_[i]->AddToList(key, value, clientid);
  }

  KVStoreStatus::type RemoveFromList(const std::string& key, const std::string& value, const std::string& clientid) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->RemoveFromList(key, value, clientid);
    }
    return ifaces_[i]->RemoveFromList(key, value, clientid);
  }

};

} // namespace

#endif
