/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "KeyValueStore_constants.h"

namespace KeyValueStore {

const KeyValueStoreConstants g_KeyValueStore_constants;

KeyValueStoreConstants::KeyValueStoreConstants() {
}

} // namespace

