/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef KeyValueStore_CONSTANTS_H
#define KeyValueStore_CONSTANTS_H

#include "KeyValueStore_types.h"

namespace KeyValueStore {

class KeyValueStoreConstants {
 public:
  KeyValueStoreConstants();

};

extern const KeyValueStoreConstants g_KeyValueStore_constants;

} // namespace

#endif
