/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Tribbler_CONSTANTS_H
#define Tribbler_CONSTANTS_H

#include "Tribbler_types.h"

namespace Tribbler {

class TribblerConstants {
 public:
  TribblerConstants();

};

extern const TribblerConstants g_Tribbler_constants;

} // namespace

#endif
