/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Tribbler_constants.h"

namespace Tribbler {

const TribblerConstants g_Tribbler_constants;

TribblerConstants::TribblerConstants() {
}

} // namespace

